app/src/lib/checks/index.js
- A missing opening bracket wasn't showing as an error because the 'isolate_punctuation' function was overwriting the error message for all '[' tokens. Moved 'isolate_punctuation' to before the bracket balancing check.
- The missing bracket messages were flipped around.
=> Fix opening bracket error and messages

app/src/lib/parser/tokenize.test.js, app/src/lib/regexes.js
Another option would be to convert all ’ to ' before tokenization.
=> Fix handling of apostrophe variant.

app/src/lib/parser/error_messages.js, app/src/lib/parser/tokenize.js, app/src/lib/parser/tokenize.test.js
- Allow punctuation after clause notation
- Allow digits after a colon
After:
=> Fix tokenizing issues.

app/src/index.d.ts, app/src/lib/lookups.js, app/src/lib/parser/index.js, app/src/lib/parser/index.test.js, app/src/lib/parser/pairings.js, app/src/lib/parser/token.js, app/src/lib/rules/checker_rules.js, app/src/lib/tokens/Pairing.svelte, app/src/lib/tokens/Result.svelte, app/src/lib/tokens/Word.svelte, app/src/routes/+page.svelte
The changes here also fix Issue #20:
Also, I made any check on a lookup word have to be true for all lookup results for a word. Because of this, the pairing level check is satisfied if any senses of the word are the right level. This inadvertently and temporarily 'fixes' Issue #25, in that it no longer results in an error:
#25 should stay open though because the root of the issue still needs fixing.
=> Move lookups into pipeline

app/src/lib/app.postcss, app/src/lib/tokens/Result.svelte
Sentence for testing:
John went-A to the store. John said, ["Go".]
went-A - links to 'go-A' (uses stem with sense)
said - links to 'say' (uses stem from inflection lookup)
store - links to 'store'
=> Add link to ontology for lookup tokens.

app/src/lib/parser/pronoun_rules.js, app/src/lib/parser/syntax.js, app/src/lib/parser/syntax.test.js, app/src/lib/parser/tokenize.js, app/src/lib/regexes.js, app/src/lib/rules/checker_rules.js
Fixes #36 and other pronoun issues.
Each-other must be hyphenated and used with a referent:
`The people fight each other. The people fight each-other. The people fight each-other(people).`
Can't use possessive mine/yours/ours. Can't use third person pronouns with a referent. Must use a recognized pronoun:
`That book is mine. John saw her(Mary). John saw asdf(person).`
=> Improve pronoun check and functionality

app/src/lib/backtranslator/index.js, app/src/lib/rules/transform_rules.js
- `_paragraph` becomes `(paragraph)`
- `God's book` becomes `the Scriptures`
- relative clauses marked with `_descriptive` get surrounded in commas (proper nouns without `_descriptive` is more complicated)
- `town//region//city//town//country named Y` becomes `X of Y`
- numbers 2/3/4/5 become two/three/four/five, respectively
Addresses most of but not all requests from #23. The others are more complex and may require using the tokenized text.
Also added a rule to fix an issue with 'named' that I discovered.
=> Resolve minor requests for the back translation.

app/src/lib/parser/tokenize.js, app/src/lib/parser/tokenize.test.js, app/src/lib/regexes.js, app/src/lib/rules/transform_rules.js, app/src/routes/form-lookup/+server.js
Fixes #52 
- Normalize input as first step of tokenize
- Fix issue with 'Did' in a question (found during testing)
-- Another case issue, 'Did' did not match 'did', so it didn't get the right form, and falsely triggering the imperative checks. Now it recognizes it as an auxiliary in a question.
`“ Did Yahweh bring us(Gideon) from Egypt? ”`
Before:
After:
=> Handle quote variants.

app/src/lib/parser/tokenize.test.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/rules_parser.js, app/src/lib/rules/transform_rules.js, app/src/routes/form-lookup/+server.js
- 'continued to' is now recognized as the aspect marker
`Moses continued to speak to the Israelites.`
- 'named' better recognizes when it is not the Verb
`A man named John obeys God named Yahweh.
John named John's son Paul.
- improve handling of 'much'. previously it always assumed it meant much-many (an adjective), but now it only assumes much-many when followed by a Noun. So now in the following sentence, 'much' is recognized as an adverb, which in turn makes 'be' be recognized as an auxiliary, which in turn no longer flags the 'two verbs' check (which is what happened in Richard's example)
`John will be much respected by people.`
- allow level 3 words within a complex alternate or pairing. 
`(complex) Those people had faith. Those people had faith. Those people had hope/faith.`
- form …
=> Fix some false errors

app/src/index.d.ts, app/src/lib/lookups.js, app/src/lib/parser/token.js, app/src/lib/regexes.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/checker_rules.test.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/rules_parser.js, app/src/lib/rules/rules_parser.test.js, app/src/lib/rules/rules_processor.test.js, app/src/lib/rules/syntax_rules.test.js, app/src/lib/rules/transform_rules.js
**Add categorization and simple rules using it**
- select the correct sense of words like by/after/before when in an Adverbial clause
- Check for brackets before adpositions that always start an adverbial clause
**Rules for determining more senses of be (including 'be like')**
**Fixed issues found with 'so'/'so-that' while testing**
- 'so-that' should be accepted as the Adposition 'so'
- 'would' within the clause indicates so-C
- 'So' at the beginning of the sentence is recognized as the conjunction
- 'so' in the subordinate clause confuses the Analyzer, so suggest using 'so-that'
- 'so that' is also accepted
**Fix lookup issue with 'following' and other potential multi-part-of-speech words**
=> Start including categorization checks

app/src/lib/parser/function_words.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/transform_rules.js, app/src/lib/tokens/Result.svelte
Added checker rules that check for simple things from the Phase 1 checklist. This is just a start.
1. Catch use of `Let's ...` for suggestive let's
2. Catch use of `Let X...` as jussive
3. Catch use of `May X...`
4. Catch use of `even`, `any`, and `really`
6. Catch use of `X's own Y`
7. Catch use of `what` as a relativizer
8. Warn about using `what` in other situations
9. Catch `where` and `whose` as relativizers
10. Suggest `all of` before non-generic nouns
11. Catch use of aspect auxilliaries with no other verb
12. Catch use of `can`
13. Catch use of `could` unless in `so-that` clause
14. Catch use of `is going to...` for future tense
15. Catch use of `has to...` or `is to...` for obligation
16. who/what now become person-A/thing-A respectively when in questions
=> Start adding checks from the P1 checklist

app/src/lib/lookups.js, app/src/lib/parser/clausify.js, app/src/lib/parser/clausify.test.js, app/src/lib/parser/function_words.js, app/src/lib/parser/index.js, app/src/lib/parser/token.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/checker_rules.test.js, app/src/lib/rules/index.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/part_of_speech_rules.test.js, app/src/lib/rules/pronoun_rules.js, app/src/lib/rules/rules_parser.js, app/src/lib/rules/rules_parser.test.js, app/src/lib/rules/rules_processor.js, app/src/lib/rules/rules_processor.test.js, app/src/lib/rules/syntax_rules.js, app/src/lib/rules/syntax_rules.test.js, app/src/lib/rules/transform_rules.js, app/src/lib/rules/transform_rules.test.js
- support searching within subtokens
- support use of shorthand 'skip groups'
- move some `syntax_rules` into more logical places
- tag patient clauses more accurately (`quote_begin`, `same_subject`, or `stand_alone`)
- support `begin` along with `start`
- Fix #83 with use of skip groups
- Show warning that a word is not yet in the ontology but should be soon (could this be the first use-case of an 'info' message?)
- support the improved api for the how-to lookup
- don't remove all other senses when selecting a sense via rules
-- Created #84 to handle a user-specified sense
=> Enhance and refactor rules.

app/src/index.d.ts, app/src/lib/lookups.js, app/src/lib/parser/index.js, app/src/lib/parser/token.js, app/src/lib/rules/case_frame/common.js, app/src/lib/rules/case_frame/index.js, app/src/lib/rules/case_frame/rules.js, app/src/lib/rules/case_frame/verbs.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/checker_rules.test.js, app/src/lib/rules/index.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/part_of_speech_rules.test.js, app/src/lib/rules/rules_parser.js, app/src/lib/rules/rules_parser.test.js, app/src/lib/rules/rules_processor.test.js, app/src/lib/rules/sense_selection_rules.js, app/src/lib/rules/syntax_rules.js, app/src/lib/rules/syntax_rules.test.js, app/src/lib/rules/transform_rules.js, app/src/lib/rules/transform_rules.test.js, app/src/lib/tokens/Result.svelte
Add case frame and sense-selection rules, and other supporting rules such as part-of-speech.
Added rules for allow/be/give/have/hear/know/say/see/speak/tell. These check the arguments present for each sense, store the missing and extra arguments, and shows appropriate messages to the user to help them find the right sense or argument structure. Support for more verbs will follow but this is a good start.
**Automatic sense selection based on case frame**
- The checkmark and x indicate which senses match the argument structure/case frame in the clause. (open to change in the UI for this)
**Automatic sense selected based on case frame and semantic keywords**
**Guide user to specify a sense if no sense matches**
**Notification of missing arguments**
**Notification of unexpected/extra …
=> Add case frame rules

app/src/index.d.ts, app/src/lib/parser/token.js, app/src/lib/rules/case_frame/common.js, app/src/lib/rules/case_frame/rules.js, app/src/lib/rules/case_frame/verbs.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/sense_selection_rules.js, app/src/lib/rules/transform_rules.js
**Add extra support needed for make/ask/tell**
- multiple possible structures for the same argument role (eg ask-A)
- show a specific message for an argument that is not written correctly (eg tell-B)
**Show a better message when an agent is missing for all senses (whether in a passive, imperative, or due to bracketing issues).**
**Fix issues with questions and passives**
- Passives that have not been checked by the case frame rules now find the agent again.
- Auxiliary be/have are now recognized when split from the verb (as in a question)
**Recognize 'so' when not at the start of a sentence as the adposition**
=> Fine tune and add case frame rules

app/src/index.d.ts, app/src/lib/lookups/index.js, app/src/lib/parser/token.js, app/src/lib/rules/case_frame/common.js, app/src/lib/rules/case_frame/rules.js, app/src/lib/rules/case_frame/verbs.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/checker_rules.test.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/pronoun_rules.js, app/src/lib/rules/rules_parser.js, app/src/lib/rules/rules_processor.js, app/src/lib/rules/sense_selection_rules.js, app/src/lib/rules/syntax_rules.js, app/src/lib/rules/transform_rules.js
- Can't use 'when' as a relativizer
- Don't allow passives in a same-subject patient clause
- Don't allow passives in an in-order-to clause
- Suggest avoiding a negative outside a cause/purpose clause
- make it a suggestion because of the explication for 'to fast' (not eat [so-that X could pray])
- Temporarily disable the level 3 (complex) because the rules can't handle it properly yet (needs to look out from current clause into all parent clauses)
(no screenshots)
- Improved handling of measurement/unit adjectives
**Before:**
**After:**
- Improve handling of surprised/amazed
- Improve handling of 'close to'
**Before:**
**After:**
- Add temporary handling of adjectives with certain Noun arguments
**Before:**
**After:**
- Handle some Nouns with noun arguments
- preparing for #100
=> Add rules and rule functionality.

app/src/lib/lookups/form.js, app/src/lib/lookups/how_to.js, app/src/lib/lookups/ontology.js
Based on the lookup search of the stem, it was finding results that should not match based on the form of the word (eg. 'covering' will never be the noun 'cover'). It usually isn't a problem due to the part-of-speech rules that filter out the wrong ones, but it doesn't always work. This PR fully resolves that issue.
**covering**
Before:
After:
**judged**
Before:
After:
**judges**
- this could still be either the verb or noun
After:
**pleased**
Before:
After:
**bowed**
Before:
After:
=> Fix false lookup matches

app/src/lib/rules/checker_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/transform_rules.js
Resolves #111 
- useful for when a word will be added to the Ontology but hasn't been yet.
- `search` is a verb in the ontology, and so creates false warnings in the sentence below, without the note. Adding _noun treats 'search' as a Noun, even though it is only known as a Verb - useful for when a word will be added to the Ontology but hasn't been yet.
=> Add part of speech disambiguating notes

app/src/lib/parser/tokenize.js, app/src/lib/parser/tokenize.test.js, app/src/lib/rules/case_frame/verbs.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/transform_rules.js
`(footnote) You(people) (imp) see Psalms 2:7.`
**Before:**
**After:**
`Because of that reason, John must go.`
`The priest must give gifts/sacrifices for-B the priest's bad-B actions [just like the priest gives gifts/sacrifices for-B the bad-B actions of the people].`
**Before:**
**After:**
- eg. for-B should always result in the Adposition because there is no Conjunction for-B
`The priest must give gifts/sacrifices for-B the priest's bad-B actions.`
**Before:**
**After:**
- 'teaching' after 'be' should actually be the Verb. By reordering the rules, it now detects the Noun after 'teaching' first before detecting the verb 'be'
`You(people) should be teaching other people about those things.`
**Before:**
**After:**
- An ambiguous word like 'judges' after 'be' is still handled correctly …
=> Minor Editor fixes

app/src/lib/rules/transform_rules.js
Fixes #116 
`Melchizedek named that man _ExplainName was the king of Salem named a city _ExplainName.`
The rule that recognized the 'named' relation was expecting a name to follow, ie a non-modified noun (eg. 'a man named Paul'). However, the _explainName structure is written with the nouns flipped, meaning the noun that follows 'named' could be any noun phrase. The 'named' rules have been adjusted to accommodate this.
Note this rule still doesn't trigger when 'named' is being used as the Verb:
`John named that man Saul.`
=> Fix 'named' phrases

app/src/index.d.ts, app/src/lib/parser/index.js, app/src/lib/parser/token.js, app/src/lib/rules/case_frame/adjectives.js, app/src/lib/rules/case_frame/common.js, app/src/lib/rules/case_frame/index.js, app/src/lib/rules/case_frame/rules.js, app/src/lib/rules/case_frame/sense_selection.js, app/src/lib/rules/case_frame/verbs.js, app/src/lib/rules/checker_rules.js, app/src/lib/rules/index.js, app/src/lib/rules/part_of_speech_rules.js, app/src/lib/rules/rules_parser.js, app/src/lib/rules/transform_rules.js
sad-A can be used attributively, predicatively, and predicatively with an argument.
because sad-B found a nominal argument, but not sad-A, it takes priority
Patient has so far not been used attributively, so it's usage does not include it. But because it has been used predicatively without an argument, it may be valid to use attributively.
Narrow has so far not been used predicatively, so it's usage does not include it. But because it has been used attributively, it may be valid to use predicatively.
=> Add adjective case frames

app/src/index.d.ts, app/src/lib/rules/case_frame/common.js, app/src/lib/rules/case_frame/sense_selection.js, app/src/lib/rules/case_frame/verbs.js, app/src/lib/rules/lookup_rules.js, app/src/lib/rules/rules_parser.js, app/src/lib/rules/rules_parser.test.js, app/src/lib/rules/transform_rules.js, app/src/routes/check/+server.js
Added case frame and sense selection rules for the following 25 verbs:
- agree
- answer
- appear
- attack
- believe
- bring
- call
- change
- choose
- cover
- die
- dream
- grow
- laugh
- learn
- lift
- look
- pray
- prepare
- promise
- return
- search
- teach
- work
- worry
Removed lookup rules that are now handled via case-frame rules.
Changed a couple transform rules to better handle neighboring Noun Phrases. This improves identifying the right Noun for Verb arguments.
- Modifying nouns such as 'gold', 'wood', 'iron', etc which indicate a 'made-of' relation are now tagged as such. eg. John had a **bronze** necklace. Only 'necklace' is a head noun. 
- 's genitives are also still not tagged as a head noun. eg. John saw **John's** house. Only 'house' is a head noun
- Previously, for a …
=> Add more verb case frames

app/src/lib/lookups/common.js, app/src/lib/lookups/form.js, app/src/lib/lookups/how_to.js, app/src/lib/lookups/ontology.js, database/inflections/to_csv.mjs
`And Christ became-C the chiefest priest of the good things [that now exist].`
'chief' is found in the form lookup, but not 'chiefest' - this form is only used within the Analyzer. The inflection is now added for this word.
Previously we added missing inflections directly into the database. In preparation for using the upcoming targets API, these missing inflections have been moved to runtime, when the form lookup is performed. These inflections won't be present in the Lexicon and thus won't be returned in the API, so we need to handle it this way anyway.
=> Fix 'chiefest' and move handling of missing inflections

app/src/lib/rules/transform_rules.js
`That faith is as valuable as our(Peter's) faith.`
Before:
After:
=> Add support for 'as Adj as...'

src/lib/parser/error_messages.js, src/lib/rules/case_frame/adjectives/presets.js, src/lib/rules/case_frame/common.js, src/lib/rules/case_frame/rules.js, src/lib/rules/case_frame/verbs/presets.js, src/lib/rules/checker_rules.js, src/lib/rules/part_of_speech_rules.js, src/lib/rules/transform_rules.js, src/routes/+page.svelte, src/routes/check/+server.js, src/routes/check/api.d.ts
eg. 'John said.'
Before:
After:
I noticed sometimes warning messages got glossed over, and this brings them more to attention.
Before:
After:
We may want to rethink the divider thing in general. We want the phase 1 people to understand that just because it passes the check doesn't mean it's perfect. And even if the editor shows errors, the text might still be ok.
Before (this should be accepted):
After:
eg. 'John slept [without eating].'
Before (should be accepted):
After:
=> Adjust some messaging

src/lib/rules/checker_rules.js, src/routes/check/+server.js
Resolves #151 
- both level 3 and level 2 words should show an error
`Those people will not enter the kingdom-B with the righteous people.`
Before:
After:
- both level 3 and level 2 words should show an error, even when in a subordinate clause
`Those people were not united by God with the people [who accepted God's message through-B faith].`
Before:
After:
- Make sure any state of tracking the complex alternate gets reset once outside the complex alternate
`(complex) Those people will not enter the kingdom-B with the people. (simple) Those people will not enter the kingdom-B with the people.`
Before:
After:
- Both level 3 and level 2 words are accepted in a complex alternate
`(complex) Those people will not enter the kingdom-B with the righteous people. (simple) Those people will not let …
=> Re-add level 3 complex word check

src/lib/rules/case_frame/adjectives/case_frames.js, src/lib/rules/case_frame/adjectives/presets.js, src/lib/rules/case_frame/sense_selection.js, src/lib/rules/part_of_speech_rules.js, src/lib/rules/transform_rules.js
Added support for more adjectives with nominal and clause arguments.
See full-B for example.
Before:
After:
Some of these rules will be able to be removed/updated when the Ontology is next updated - Tod has already made the changes on his machine. They are marked as TODOs within the code.
Also improved a couple part-of-speech disambiguations.
=> Add more adj case frames

src/lib/rules/case_frame/adjectives/case_frames.js, src/lib/rules/case_frame/verbs/case_frames.js
Improved the handling of empty theta grids to take into account any hard-coded rules for that sense - previously parts of it were being ignored. That way the editor code can specify that fail-B takes a patient clause, even when the ontology does not. This makes the sentence from the description pass the checker.
- `I(Paul) do not mean-E [God failed [to (implicit-situational) complete/fulfill the promise of God]].`
In fact, fail-B already had a rule, so this code simply gives it effect.
Resolves #158
=> Improve handling of empty theta grids

src/index.d.ts, src/lib/lookup_filters.js, src/lib/rules/case_frame/adjectives/case_frames.js, src/lib/rules/case_frame/adpositions/case_frames.js, src/lib/rules/case_frame/case_frame.d.ts, src/lib/rules/case_frame/common.js, src/lib/rules/case_frame/rules.js, src/lib/rules/case_frame/sense_selection.js, src/lib/rules/case_frame/verbs/case_frames.js, src/lib/rules/checker_rules.js, src/lib/token.js, src/routes/check/+server.js, src/routes/check/api.d.ts
Check that complex pairings have a compatible case frame with the simple word. Select the sense accordingly. Flag as an error otherwise. Resolves #159 .
Also refactored a bit and improved type definitions.
- `John told/announced the people about the new law.` ✅ 
- the sense of announce compatible with the selected sense of tell is selected
- `John said/announced to the people [John was angry].` ❌ 
- announce-B, which is the expected pairing, does not support a destination, and so is flagged
- `John said/announced [John was angry].` ✅ 
- The above sentence is corrected, and the correct sense of announce is selected
- `John said/announced, ["I(John) am angry."]` ✅ 
- Again, the correct sense of announce is selected
- `Jesus saves/saves-C people from enemies.` ❌ 
- save-C cannot take a …
=> Check case frames of complex pairings.

src/lib/rules/case_frame/common.js, src/lib/rules/case_frame/rules.js, src/lib/rules/case_frame/sense_selection.js, src/lib/rules/case_frame/verbs/case_frames.js, src/lib/rules/case_frame/verbs/presets.js, src/lib/rules/checker_rules.js
- `John attracted many people.` - no sense has a theta grid
- `John caught-E the ball.` - the selected sense has no theta grid
- `John will destroy/demolish the building.` - the complex pairing has no theta grid
- `John ate the bread for Mary.`
beg
begin
blame
borrow
build
bury
catch
chase
chase-away
hang
hate
hide
hope
increase
invite
join
keep
know-how
lead
learn-how
let
lie
listen
mean
move
need
notice
offer
open
order
pass
pay
persuade
plan
please
point
pour
pour-out
praise
prevent
protect
pull
put
read
refuse
remember
remind
reply
run
scream
seem
sell
separate
shine
shoot
shout
show
show-how
sing
smell
sound-like
spill
sprinkle
start
struggle
suggest
take-away
talk
taste
teach-how
tear
thank
trust
try
turn
understand
wait
walk
warn
watch
watch-out
weigh
wrap
write
=> Add more verb theta grids
